### ISSUE TITLE
Include default configuration values

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-liquibase#25]
Looking at the config docs it's not clear what values these properties are set to by default

https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html#io.micronaut.configuration.dbmigration.liquibase.LiquibaseConfigurationProperties

Edit:
I see now that some say things like \"Default value (true)." in the description. I missed this at first. It'd be easier to spot and to consume as its own column. There are also still a lot where no default is included

**Comment by ilopmar** [comment]
That table is generated automatically from the javadoc.
