### ISSUE TITLE
Micronaut liquibase missin in maven central repositories

### ISSUE THREAD

**Issue by miledean** [micronaut-projects/micronaut-liquibase#7]
Hi, it looks like micronaut-liquibase is missing from maven central repositories. Not sure if this is temporary issue.
See here: https://repo.maven.apache.org/maven2/io/micronaut/configuration/
https://repo.maven.apache.org/maven2/io/micronaut/configuration/micronaut-liquibase/

**Comment by ilopmar** [comment]
@miledean Thanks for the issue. We'll try to publish it to Maven central.
In the mean time you can grab it from jcenter: https://bintray.com/micronaut/core-releases-local/liquibase

**Comment by ilopmar** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-liquibase/commit/c08a0f6818b76def2073a4ccad55ba6d9950873b.

We have also published the latest version to Maven Central: https://repo.maven.apache.org/maven2/io/micronaut/configuration/micronaut-liquibase/
