### ISSUE TITLE
Documentation on How to Execute Migrations

### ISSUE THREAD

**Issue by fny** [micronaut-projects/micronaut-liquibase#86]
Thanks for building this integration! I haven't, however, been able to figure out how to run any of the commands to migrate the database. It would be great if there was some documentation on this.

**Comment by sdelamo** [comment]
@fny for running the commands learning about liquibase commands, [liquibase documentation](https://www.liquibase.org/get-started) is the place to go. Is that what you where looking for?

**Comment by fny** [comment]
Yes. I was mistakenly under the impression that the integration added
commands under a micronaut namespace.
